FROM maven:latest as build
WORKDIR /build
COPY . .
RUN mvn clean package
FROM java:8
WORKDIR /opt/Transactions
COPY --from=build /build/target/Transcations-0.0.1-SNAPSHOT.jar Transactions.jar
EXPOSE 9006
ENTRYPOINT ["/usr/bin/java", "-jar", "Transactions.jar"]

