FROM maven:latest as build
WORKDIR /build
COPY . .
RUN mvn clean package
FROM java:8
WORKDIR /opt/AuditProducerBE
COPY --from=build /build/target/AuditProducerBE-0.0.1-SNAPSHOT.jar AuditProducer.jar
EXPOSE 9002
ENTRYPOINT ["/usr/bin/java", "-jar", "AuditProducer.jar"]

