FROM maven:latest as build
WORKDIR /build
COPY . .
RUN mvn clean package
FROM java:8
WORKDIR /opt/AuditConsumerBE
COPY --from=build /build/target/AuditBE-0.0.1-SNAPSHOT.jar AuditConsumer.jar
EXPOSE 9010
ENTRYPOINT ["/usr/bin/java", "-jar", "AuditConsumer.jar"]

