FROM maven:latest as build
WORKDIR /build
COPY . .
RUN mvn clean package
FROM java:8
WORKDIR /opt/ANPR
COPY --from=build /build/target/ANPR-0.0.1-SNAPSHOT.jar ANPR.jar
EXPOSE 9005
ENTRYPOINT ["/usr/bin/java", "-jar", "ANPR.jar"]

